linters:
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - gocyclo
    - gosec

run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude:
    - "^examples/.*"
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    enable-all: true
  misspell:
    locale: US
  revive:
    rules:
      - name: package-comments
      - name: exported
